# Configuration for standard GitHub Actions runners
# This file configures the default runner scale set

# Runner Scale Set Configuration
runnerSet:
  # Name of the runner set
  name: "standard-runners"
  
  # Repository or organization to deploy runners for
  # Uncomment and set one of these:
  # repository: "your-org/your-repo"
  organization: "your-org"
  # enterprise: "your-enterprise"
  
  # Runner labels for job targeting
  labels:
    - "self-hosted"
    - "linux"
    - "x64"
    - "standard"
  
  # Number of replicas (runners)
  replicas: 2
  
  # Minimum number of replicas
  minReplicas: 1
  
  # Maximum number of replicas
  maxReplicas: 10
  
  # Standard runner image
  image: "ghcr.io/actions/actions-runner:latest"
  
  # Docker configuration
  docker:
    enabled: true
    dockerdWithinRunnerContainer: false
    mtu: 1500
    mirror: ""
  
  # Runner resources
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  
  # Runner environment variables
  env:
    - name: RUNNER_LABELS
      value: "standard,linux,x64"
    - name: RUNNER_GROUP
      value: "standard-runners"
  
  # Working directory
  workDir: "/runner/_work"
  
  # Auto-scaling configuration
  autoscaling:
    enabled: true
    # Horizontal Pod Autoscaler configuration
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
      scaleDownDelaySecondsAfterAdd: 300
      scaleDownDelaySecondsAfterDelete: 300
      scaleDownDelaySecondsAfterFailure: 180
      scaleDownUnneededTimeSeconds: 600
      scaleDownUtilizationThreshold: 0.5
    
    # Behavior configuration
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 4
            periodSeconds: 15
        selectPolicy: Max

# AKS-specific configurations
aks:
  # Use Azure CNI
  useAzureCNI: true
  
  # Azure storage class
  storageClass: "managed-premium"
  
  # Azure node pool configuration
  nodePool:
    # Node pool name for runners
    name: "standard-runner-pool"
    
    # Node pool labels
    labels:
      node.kubernetes.io/instance-type: "Standard_D4s_v3"
    
    # Node pool taints
    taints: []
    
    # Node pool annotations
    annotations: {}

# Monitoring and logging
monitoring:
  enabled: true
  
  # Pod disruption budget
  pdb:
    enabled: true
    minAvailable: 1

# Pod disruption budget
pdb:
  enabled: true
  minAvailable: 1 