{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "runner-set.fullname" . }}-pdb
  labels:
    {{- include "runner-set.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "runner-set.selectorLabels" . | nindent 6 }}
{{- end }} 