{{- if .Values.runnerSet.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runner-set.serviceAccountName" . }}
  labels:
    {{- include "runner-set.labels" . | nindent 4 }}
  {{- with .Values.runnerSet.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 