{{- if .Values.controller.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-runner-controller.serviceAccountName" . }}-controller
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-controller
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "secrets", "configmaps", "services", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["actions.summerwind.dev"]
    resources: ["runners", "runnerdeployments", "runnersets", "runnerreplicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-controller
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "github-runner-controller.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "github-runner-controller.serviceAccountName" . }}-controller
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.webhook.enabled and .Values.webhook.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-runner-controller.serviceAccountName" . }}-webhook
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-webhook
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-webhook
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "github-runner-controller.fullname" . }}-webhook
subjects:
  - kind: ServiceAccount
    name: {{ include "github-runner-controller.serviceAccountName" . }}-webhook
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.metrics.enabled and .Values.metrics.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-runner-controller.serviceAccountName" . }}-metrics
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-metrics
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["actions.summerwind.dev"]
    resources: ["runners", "runnerdeployments", "runnersets", "runnerreplicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-metrics
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "github-runner-controller.fullname" . }}-metrics
subjects:
  - kind: ServiceAccount
    name: {{ include "github-runner-controller.serviceAccountName" . }}-metrics
    namespace: {{ .Release.Namespace }}
{{- end }} 