apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-runner-controller.fullname" . }}-controller
  labels:
    {{- include "github-runner-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "github-runner-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller 